[package]
name = "nano-p2p"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
nano-chainstate = { path = "../nano-chainstate", default-features = false }
nano-codec = { path = "../nano-codec" }
nano-consensus-profile = { path = "../nano-consensus-profile" }
nano-crypto = { path = "../nano-crypto" }
nano-primitives = { path = "../nano-primitives" }
nano-queue = { path = "../nano-queue" }
rusqlite = { version = "0.31.0", features = ["bundled"] }
tokio = { version = "1.53.1", default-features = false, features = ["io-util", "net", "time"] }

[dev-dependencies]
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
