[package]
name = "nano-chainstate"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
clarity = { git = "https://github.com/stacks-network/stacks-core.git", rev = "e04ba8e101fe2f71fae9c79a956b599e0523f3ae" }
nano-address = { path = "../nano-address" }
nano-marf = { path = "../nano-marf" }
nano-codec = { path = "../nano-codec" }
nano-crypto = { path = "../nano-crypto" }
nano-primitives = { path = "../nano-primitives" }
nano-sortition = { path = "../nano-sortition" }
nano-vm = { path = "../nano-vm" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[lints]
workspace = true
