[package]
name = "nano-chainstate"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
clarity = { git = "https://github.com/stacks-network/stacks-core.git", rev = "efc34a07a225c4b950ab9404a1652aa5e14affaf" }
hex = "0.4.3"
nano-address = { path = "../nano-address" }
nano-bitcoin = { path = "../nano-bitcoin" }
nano-marf = { path = "../nano-marf" }
nano-codec = { path = "../nano-codec" }
nano-crypto = { path = "../nano-crypto" }
nano-primitives = { path = "../nano-primitives" }
nano-sortition = { path = "../nano-sortition" }
nano-vm = { path = "../nano-vm" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[lints]
workspace = true
