[package]
name = "nano-conformance"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
nano-address = { path = "../nano-address" }
nano-bitcoin = { path = "../nano-bitcoin" }
nano-codec = { path = "../nano-codec" }
nano-chainstate = { path = "../nano-chainstate" }
nano-crypto = { path = "../nano-crypto" }
nano-marf = { path = "../nano-marf" }
nano-node = { path = "../nano-node" }
nano-primitives = { path = "../nano-primitives" }
nano-signer = { path = "../nano-signer" }
nano-sortition = { path = "../nano-sortition" }
nano-stackerdb = { path = "../nano-stackerdb" }
nano-vm = { path = "../nano-vm" }
hex = "0.4.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
nano-codec = { path = "../nano-codec" }
nano-mempool = { path = "../nano-mempool" }
nano-sync = { path = "../nano-sync" }
reqwest = { version = "0.13.4", default-features = false }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time"] }
clarity = { git = "https://github.com/stacks-network/stacks-core.git", rev = "efc34a07a225c4b950ab9404a1652aa5e14affaf" }
libstackerdb = { git = "https://github.com/stacks-network/stacks-core.git", rev = "efc34a07a225c4b950ab9404a1652aa5e14affaf" }
libsigner = { git = "https://github.com/stacks-network/stacks-core.git", rev = "efc34a07a225c4b950ab9404a1652aa5e14affaf" }
proptest = "1.11.0"
stacks-common = { git = "https://github.com/stacks-network/stacks-core.git", rev = "efc34a07a225c4b950ab9404a1652aa5e14affaf" }
stackslib = { git = "https://github.com/stacks-network/stacks-core.git", rev = "efc34a07a225c4b950ab9404a1652aa5e14affaf", features = ["testing"] }

[lints]
workspace = true
