[package]
name = "nano-bitcoin"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bitcoin = "0.32.8"
bitcoincore-rpc = "0.19.0"
nano-address = { path = "../nano-address" }
nano-crypto = { path = "../nano-crypto" }
sha2 = "0.10.9"

[dev-dependencies]
hex = "0.4.3"
nano-primitives = { path = "../nano-primitives" }

[lints]
workspace = true
