[package]
name = "nano-bitcoin"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bitcoin = "0.32.8"
nano-address = { path = "../nano-address" }
nano-crypto = { path = "../nano-crypto" }

[dev-dependencies]
hex = "0.4.3"
nano-primitives = { path = "../nano-primitives" }

[lints]
workspace = true
