[package]
name = "nano-node"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nano-bitcoin = { path = "../nano-bitcoin" }
nano-chainstate = { path = "../nano-chainstate" }
nano-sortition = { path = "../nano-sortition" }

[lints]
workspace = true
