[package]
name = "nano-stackerdb"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
nano-address = { path = "../nano-address" }
nano-chainstate = { path = "../nano-chainstate" }
nano-codec = { path = "../nano-codec" }
nano-crypto = { path = "../nano-crypto" }
nano-primitives = { path = "../nano-primitives" }
hex = "0.4.3"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "native-tls"] }
serde = { version = "1.0.229", features = ["derive"] }

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
